### ISSUE TITLE
Använd .lower() när du jämför strängar med användarens input

### ISSUE THREAD

**Issue by einarpersson** [linneakarlstrom/Login-system#1]
Bra jobbat!

En sak:

```
        if username_again == "yes" or username_again == "Yes":
            login = True
        if username_again == "No" or  username_again == "no":
```
För att hantera "yes" och "Yes" och "YES" och "yEs" etc. så kan du använda string-metoden `.lower()` så fort du tar in input från användaren. https://www.tutorialspoint.com/python/string_lower.htm

Se även första svaret på denna fråga: https://stackoverflow.com/questions/12719586/how-to-let-python-recognize-both-lower-and-uppercase-input

**Comment by linneakarlstrom** [comment]
Tror att jag har fixat det nu.
